Added business logic into CoffeeConroller
DiskReader/CoffeeShop pull request #3
Opened 2022-07-06 10:43 UTC by DiskReader

2022-07-06 11:46 UTC, hromau requested changes

2022-07-06 11:46 UTC, hromau commented on CoffeeShop/Controllers/CoffeeController.cs
> +                throw new ArgumentException("Entered data is not correct", nameof(coffee));
duplicated code. let's think about that

2022-07-06 11:46 UTC, hromau commented on CoffeeShop/Controllers/CoffeeController.cs
>          public void PostNewCoffee([FromBody]Coffee coffee)
post new cofee?

2022-07-06 11:46 UTC, hromau commented on CoffeeShop/Controllers/CoffeeController.cs
> +        public void PutById(int id, [FromBody]Coffee coffee)
and put by id?

2022-07-06 11:59 UTC, hromau requested changes

2022-07-06 11:59 UTC, hromau commented on CoffeeShop/Context/CoffeeShopContext.cs
> +                    .HasMaxLength(30)
do u create migration on this change?

2022-07-06 12:21 UTC, DiskReader commented on CoffeeShop/Context/CoffeeShopContext.cs
> +                    .HasMaxLength(30)
yep

2022-07-06 12:28 UTC, CrazyKamenwik approved these changes

2022-07-06 14:39 UTC, pavelGagarin0870 approved these changes

2022-07-07 09:41 UTC, hromau approved these changes

2022-07-07 09:43 UTC, merged