moved db interactions into CoffeeShopRepository
DiskReader/CoffeeShop pull request #7
Opened 2022-07-08 14:38 UTC by DiskReader

2022-07-08 15:33 UTC, GodlyCat approved these changes

2022-07-11 08:32 UTC, hromau requested changes

2022-07-11 08:32 UTC, hromau commented on CoffeeShop/Repositories/CoffeeShopRepository.cs
> +        public async Task<Coffee> GetCoffeeById(int id)
why another methods is sync and this is async?

2022-07-11 08:32 UTC, hromau commented on CoffeeShop/Repositories/CoffeeShopRepository.cs
> +        public async Task<Coffee> GetCoffeeById(int id)
if u have async and sync methods, u should add async postfix, like NameOfMehtodAsync

2022-07-11 09:33 UTC, DiskReader commented on CoffeeShop/Repositories/CoffeeShopRepository.cs
> +        public async Task<Coffee> GetCoffeeById(int id)
> why another methods is sync and this is async?

I need this method async to show that my custom exception middleware can handle exceptions. If this method be sync -- exception will not rich it

2022-07-11 10:20 UTC, hromau approved these changes

2022-07-11 10:20 UTC, merged